### ISSUE TITLE
Doesn't open when the round has ended

### ISSUE THREAD

**Issue by Oyplap** [lumien231/Lumiens-Map-Vote#2]
The map vote doesn't open when the round has ended in deathrun. Could you fix or add that?

Kind regards,
Oyplap

**Comment by lumien231** [comment]
> Since i only modified this addon for one specific server I will not fix issues in gamemodes other than TTT. (Though i will accept PRs for them)

Sorry 😅

**Comment by Oyplap** [comment]
Found the solution if someone has the same issue:

Step 1: Go to "garrysmod\addons\Lumiens-Map-Vote-master\lua\autorun\server"

Step 2: Create a lua file called "sv_hooks.lua"

Step 3: put this inside the file:
hook.Add("DeathrunStartMapvote", "Start map voting", function(rounds)
    MapVote.Start(nil, nil, nil, nil)
    return true
end )

Step 4: Enjoy!
